# Generated by Django 2.2.1 on 2020-01-22 13:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20200122_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='id',
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='nationalCode',
            field=models.CharField(default=django.utils.timezone.now, max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
